spring:
  application:
    name: demo12
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://Zanila:salsita123@cluster0.damyqxk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGO_DB_NAME:collita}
      auto-index-creation: true

  main:
    allow-bean-definition-overriding: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.desarrollomovil.demo12: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 